### ISSUE TITLE
Can't Not Apply Language On 4.0.2

### ISSUE THREAD

**Issue by whitebear13579** [Epicnicity322/PlayMoreSounds#5]
Hello, I recently used PlayMoreSounds 4.0.2 on my server and tried to make a language translation package myself. I found that I couldn’t apply it (I renamed the file myself). Not only that, but I even spoke Spanish and simplified Chinese. The built-in translation files of the plug-in can’t be applied. I would like to ask if this is a bug?

**Comment by chrisrnj** [comment]
Hello, turns out I made so the plugin looks up for the key 'Language' in config instead of 'Language Locale' and forgot to update it. I'll update the config so this key is generated as 'Language' in the next update, meanwhile you can just rename 'Language Locale' key to 'Language' in your config and the language will be changed.

If you're making a new translation make sure it has the name of one of the 4 current language files, as keys in the 'Language' option can only be EN_US, ES_LA, PT_BR or ZH_CN.
If you'd like to contribute to the plugin with your translation, send it to me and I'll add it with it's own locale key.

**Comment by chrisrnj** [comment]
Fixed on a483ebdcedf094af1561e58a45d53b8c87a487c2
